# Info
title: D! Journal
description: "I collect, create and share  STORIES, IDEAS, TUTORIALS,TOOLS<br>and all kinds of RESOURCES to get inspired, learn and have fun."

# Setup
url: http://lab.diogorusso.com
baseurl: /guides

# Permalinks
permalink: /:title.html
# relative_permalinks: true

# Sass
sass:
  sass_dir: _assets/scss
  style: :compressed

# Media CDN (cloudinary)
cdn: http://res.cloudinary.com/diogorusso/image/upload/
preloader: https://digitalsynopsis.com/wp-content/uploads/2016/06/loading-animations-preloader-gifs-ui-ux-effects-18.gif

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      cover: "023_o3i5iz.jpg"
      notes:
        - Display hidden files on mac
        - 023_o3i5iz
        - 023_o3i5iz
      topics:
        - Installing Xcode Commandline
        - Basics of Apple Terminal
        - Creat and Config Bash Profile
        - What's Bash RC
        - Displaying hidden files
        - Homebrew Installation
        - Homebrew Basics
        - Homebrew Cask
      links:
        - desc: "Are you switching to VSCode and looking for some useful extensions? Below is a collection of my favorite VSCode extensions."
          url: "https://ihatetomatoes.net/collection-of-useful-extensions-for-vscode/"
        - desc: "VSCode tutorial that will walk your through the VSCode interface and introduce handy keyboard shortcuts."
          url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"
        - desc: "Xcode is a large suite of software development tools and libraries from Apple."
          url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"
        - desc: "Are you switching to VSCode and looking for some useful extensions? Below is a collection of my favorite VSCode extensions."
          url: "https://ihatetomatoes.net/collection-of-useful-extensions-for-vscode/"
        - desc: "Are you switching to VSCode and looking for some useful extensions? Below is a collection of my favorite VSCode extensions."
          url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"

# Content Structure (categories)
content:
  - cat: Art Studio
    sub:
      - Raw
      - Catalogue
      - Gallery
      - Events
  - cat: Code Camp
    sub:
      - Dev Setup
      - Jekyll Sites
      - Databases
      - Applications
  - cat: Design Lab
    sub:
      - Logos
      - Tipography
      - Graphics
      - Interaction
  - cat: Creative Office
    sub:
      - Venture Design
      - Product Design
      - Experience Design
      - Impact 

exclude: [gulpfile, package.json,package-lock.json, node_modules,Gemfile,Gemfile.lock]