# Url
url: https://lab.diogorusso.com
baseurl: /guides


# Info
author: "Diogo Russo"
title: "Diogo Russo - Product Design"
description: "I'm a designer, artist and storyteller, an optimist dedicated to help bringing ideas to life."
# description: "I like sharing inspiration, resources and insights of what it takes to bring ideas to life."
keywords: "Diogo Russo, Product Desig, UX Design, Graphic Design, Visual Arts"

# Media CDN (cloudinary)
cdn: https://res.cloudinary.com/diogorusso/image/upload/
# cdn: /guides/assets/img/
profile: about/bio/diogorusso.jpg
ico: favicons/favicon.ico
svg: favicons/favsvg.svg
512x512: favicons/icon-512x512.png
310x310: favicons/icon-310x310.png
192x192: favicons/icon-192x192.png
180x180: favicons/icon-180x180.png
150x150: favicons/icon-150x150.png
144x144: favicons/icon-144x144.png
70x70: favicons/icon-70x70.png
310x150: favicons/icon-310x150.png

# Content Structure (categories - use to build sidebar)
content:
  - cat: Ideas
    sub:
      - Studies
      - Gallery
      - Inspiration
      - Store
      # - Events
  - cat: Projects
    sub:
      - Webdesign
      - Applications
      - Playground      
  - cat: Toolkit
    sub:
      - Logos
      - Tipography
      - Graphics
      - Interaction
  - cat: Learn
    sub:
      - Venture Design
      - Product Design
      - Experience Design

work:
  - cat: "Creative Direction"
    description: 
  - cat: "Experience and Product"
    description:
  - cat: "Web and Graphics"
    description:
  - cat: "Illustration and Artwork"
    description:

# Post Defaults
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post/learn'
      cover: "journal/v1517095743/django-blog-basic.jpg"
      topics:
        - topic: Key localization elements
          notes:
            - url: note_plc.jpg
              description: "Python workflow diagram"
            - url: note_plc.jpg
              description: "Python workflow diagram"
          links: 
            - description: "Adapting graphics to meet target markets Modifying content to suit the tastes and consumption habits of other markets Adapting design and layout to properly display translated text "
              url: "https://ihatetomatoes.net/collection-of-useful-extensions-for-vscode/"
            - description: "Converting to local requirements (such as currencies and units of measure) Using proper local formats for dates, addresses, and phone numbers. Addressing local regulations and legal requirements"
              url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"
            - description: "VSCode tutorial that will walk your through the VSCode interface and introduce handy keyboard shortcuts."
              url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"
            - description: "VSCode tutorial that will walk your through the VSCode interface and introduce handy keyboard shortcuts."
              url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"
        - topic: Key localization elements
          notes:
            - url: note_plc.jpg
              description: "Python workflow diagram"
            - url: note_plc.jpg
              description: "Python workflow diagram"
          links: 
            - description: "Adapting graphics to meet target markets Modifying content to suit the tastes and consumption habits of other markets Adapting design and layout to properly display translated text "
              url: "https://ihatetomatoes.net/collection-of-useful-extensions-for-vscode/"
            - description: "Converting to local requirements (such as currencies and units of measure) Using proper local formats for dates, addresses, and phone numbers. Addressing local regulations and legal requirements"
              url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"
            - description: "VSCode tutorial that will walk your through the VSCode interface and introduce handy keyboard shortcuts."
              url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"
            - description: "VSCode tutorial that will walk your through the VSCode interface and introduce handy keyboard shortcuts."
              url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"
       
##### CONFIG  #####

# Exclude
exclude: [gulpfile, package.json,package-lock.json, node_modules,Gemfile,Gemfile.lock, README.md]

# Permalinks
# permalink: /:title.html
permalink: /:categories/:title.html
# relative_permalinks: true

# Sass
sass:
  sass_dir: _includes/scss
  style: :compressed