# Setup
url: http://lab.diogorusso.com
baseurl: /guides

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:title.html
# relative_permalinks: true

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _assets/scss
  style: :compressed

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      thumb: "https://i.warosu.org/data/g/img/0549/19/1465123514962.jpg"
      cover: "https://embedwistia-a.akamaihd.net/deliveries/d5ae8190f0aa7dfbe0b01f336f29d44094b967b5.jpg"

#Info
title: D! Journal
description: "I collect, create and share  STORIES, IDEAS, TUTORIALS,TOOLS<br>and all kinds of RESOURCES to get inspired, learn and have fun."

#Lists
content:
  - cat: Art Studio
    sub:
      - Raw
      - Catalogue
      - Gallery
      - Events
  - cat: Code Camp
    sub:
      - Dev Setup
      - Jekyll Sites
      - Databases
      - Applications
  - cat: Design Lab
    sub:
      - Logos
      - Tipography
      - Graphics
      - Interaction
  - cat: Creative Office
    sub:
      - Venture Design
      - Product Design
      - Experience Design
      - Impact 

