
##### CONFIG  #####

# Exclude
exclude: [gulpfile, package.json,package-lock.json, node_modules,Gemfile,Gemfile.lock, README.md]

# Permalinks
# permalink: /:title.html
permalink: /:categories/:title.html
# relative_permalinks: true

# Sass
sass:
  sass_dir: _includes/scss
  style: :compressed


##### SITE  #####

# Info
title: D! Journal
description: "I collect, create and share  STORIES, IDEAS, TUTORIALS,TOOLS<br>and all kinds of RESOURCES to get inspired, learn and have fun."

# Setup 
url: http://lab.diogorusso.com
baseurl: /guides


# Media CDN (cloudinary)
# cdn: http://res.cloudinary.com/diogorusso/image/upload/
cdn: /guides/assets/img/
preloader: guides/assets/preloader.svg

# Nanigation


# Content Structure (categories - use to build sidebar)
content:
  - cat: Art Studio
    sub:
      - Studies
      - Gallery
      - Inspiration
      - Store
      # - Events
  - cat: Code Camp
    sub:
      - Webdesign
      - Applications
      - Playground      
  - cat: Design Lab
    sub:
      - Logos
      - Tipography
      - Graphics
      - Interaction
  - cat: Creative Office
    sub:
      - Venture Design
      - Product Design
      - Experience Design

work:
  - cat: "Creative Direction"
    description: 
  - cat: "Experience and Product"
    description:
  - cat: "Web and Graphics"
    description:
  - cat: "Illustration and Artwork"
    description:

# Post Defaults
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post/learn'
      cover: "journal/v1517095743/django-blog-basic.jpg"
      topics:
        - topic: Key localization elements
          notes:
            - url: note_plc.jpg
              description: "Python workflow diagram"
            - url: note_plc.jpg
              description: "Python workflow diagram"
          links: 
            - description: "Adapting graphics to meet target markets Modifying content to suit the tastes and consumption habits of other markets Adapting design and layout to properly display translated text "
              url: "https://ihatetomatoes.net/collection-of-useful-extensions-for-vscode/"
            - description: "Converting to local requirements (such as currencies and units of measure) Using proper local formats for dates, addresses, and phone numbers. Addressing local regulations and legal requirements"
              url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"
            - description: "VSCode tutorial that will walk your through the VSCode interface and introduce handy keyboard shortcuts."
              url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"
            - description: "VSCode tutorial that will walk your through the VSCode interface and introduce handy keyboard shortcuts."
              url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"
        - topic: Key localization elements
          notes:
            - url: note_plc.jpg
              description: "Python workflow diagram"
            - url: note_plc.jpg
              description: "Python workflow diagram"
          links: 
            - description: "Adapting graphics to meet target markets Modifying content to suit the tastes and consumption habits of other markets Adapting design and layout to properly display translated text "
              url: "https://ihatetomatoes.net/collection-of-useful-extensions-for-vscode/"
            - description: "Converting to local requirements (such as currencies and units of measure) Using proper local formats for dates, addresses, and phone numbers. Addressing local regulations and legal requirements"
              url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"
            - description: "VSCode tutorial that will walk your through the VSCode interface and introduce handy keyboard shortcuts."
              url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"
            - description: "VSCode tutorial that will walk your through the VSCode interface and introduce handy keyboard shortcuts."
              url: "https://www.youtube.com/watch?v=5irqj-YVo4M&list=PLkEZWD8wbltm8T3mS7SMCpT6WlnyIP50T"
       

