# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:title.html
# relative_permalinks: true

# Setup
url: http://lab.diogorusso.com
baseurl: /guides

#Info
title: D! Journal
description: Basic example of a Jekyll site with Sass enabled.

#Lists
code-camp:
  - Setup
  - Databases
  - Static Websites
  - Applications

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _assets/scss
  style: :compressed
